apiVersion: microcks.io/v1alpha1
kind: Microcks
metadata:
  name: microcks
  namespace: microcks
spec:
  version: 1.12.1
  microcks:
    url: microcks.34.120.54.115.sslip.io
    grpcIngress:
      expose: false
  keycloak:
    url: keycloak.34.8.172.33.sslip.io
    privateUrl: http://microcks-keycloak.microcks.svc.cluster.local:8080
  mongodb:
      persistent: true
      volumeSize: 1Gi
      storageClassName: standard-rwo
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
  features:
    aiCopilot:
      enabled: false
      implementation: openai
      openai:
        apiKey: ""
        timeout: 30
        model: gpt-3.5-turbo
        maxTokens: 2000