apiVersion: tests.testkube.io/v1
kind: TestTrigger
metadata:
  name: microcks-testtrigger-pastry
  namespace: testkube
spec:
  action: run
  event: modified
  execution: testworkflow
  resource: deployment
  resourceSelector:
    labelSelector:
      matchLabels:
        app: quarkus-api-pastry
  testSelector:
    name: microcks-test-pastry
    namespace: testkube