apiVersion: lifecycle.keptn.sh/v1
kind: KeptnTaskDefinition
metadata:
  name: testkube-microcks-runner
  namespace: default
spec:  
  container:
    name: testkube-runner
    image: kubeshop/testkube-cli:latest
    command:
    - 'sh'
    - '-c'
    - |
      # run the Microcks test workflow with Testkube
      testkube run tw microcks-test-pastry -f