kind: TestWorkflow
apiVersion: testworkflows.testkube.io/v1
metadata:
  name: k6-test-microservice
  namespace: testkube
  labels:
    test-workflow-templates: "yes"
    testkube.io/group: demo
    testkube.io/name: k6
spec:
  use:
  - name: official/k6/v1
    config:
      run: k6 run src/k6/k6-test-microservice.js
  content:
    git:
      uri: https://github.com/lreimer/hands-on-testkube.git
  container:
    workingDir: /data/repo
    env:
    - name: TARGET_HOSTNAME
      value: hands-on-testkube.default.svc.cluster.local
status: {}
