apiVersion: tests.testkube.io/v1
kind: TestTrigger
metadata:
  name: testtrigger-nginx
  namespace: testkube
spec:
  action: run
  event: modified
  execution: testworkflow
  resource: deployment
  resourceSelector:
    labelSelector:
      matchLabels:
        app: nginx
  testSelector:
    name: k6-test-nginx
    namespace: testkube